site_name: OpenMusic
copyright: "a cool project by ADGSTUDIOS - crafted with ❤️ from Ashlin Darius Govindasamy"
site_url: https://adgstudios.com
repo_url: https://github.com/ADGSTUDIOS/OpenMusic
repo_name: ADGSTUDIOS/OpenMusic
nav:
      - General Information:
        - Introduction: index.md
        - Real World Examples: real-world-examples.md

      - Technical Walkthrough and Documentation:
        - Downloading files: downloadingfiles.md
        - Configuration: configuration.md
        - Development: development.md
        - Deployment: deployment.md

      - Getting Started - GitHub Way (User Friendly Way):
            - Linux Setup (Recommended for Intermediate Level Users): visual-linux.md 
            - Docker Setup (recommended for DevOps Guys): docker-guide.md
  
theme:
      name: material
      highlightjs: true
      hljs_languages:
            - yaml
      icon:
            repo: fontawesome/brands/github
      navigation_depth: 6
      titles_only: false
      favicon: ./static/favicon.svg
      logo: ./static/logo.png
      features:
            - navigation.instant
      palette:
            - media: "(prefers-color-scheme: light)"
              scheme: default
              toggle:
                    icon: material/weather-sunny
                    name: Switch to dark mode
            - media: "(prefers-color-scheme: dark)"
              scheme: slate
              primary: red
              toggle:
                    icon: material/weather-night
                    name: Switch to light mode
markdown_extensions:
      - toc:
              permalink: "#"
      - smarty
      - admonition
      - footnotes
      - codehilite
      - pymdownx.arithmatex
      - pymdownx.betterem:
              smart_enable: all
      - pymdownx.caret
      - pymdownx.critic
      - pymdownx.details
      - pymdownx.emoji:
              emoji_generator: !!python/name:pymdownx.emoji.to_svg
      - pymdownx.inlinehilite
      - pymdownx.magiclink
      - pymdownx.mark
      - pymdownx.smartsymbols
      - pymdownx.superfences
      - pymdownx.tasklist:
              custom_checkbox: true
      - pymdownx.tilde
      - fontawesome_markdown
extra:
      social:
            - icon: fontawesome/brands/github
              link: "https://github.com/ADGSTUDIOS"
            - icon: fontawesome/brands/linkedin
              link: "https://www.linkedin.com/in/adgsenpai/"
      manifest: "static/site.webmanifest"